/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esiee.mbdaihm.view;

import com.esiee.mbdaihm.datamodel.countries.Country;
import java.util.List;

/**
 *
 * @author student
 */
public class WorldApp extends javax.swing.JFrame {

    private List<Country> countries;
    
    /**
     * Creates new form WorldApp
     */
    public WorldApp() {
        initComponents();
        menuLeft1.setMap(mapPanel1);
        menuLeft1.setLegend(legend1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLeft1 = new com.esiee.mbdaihm.view.MenuLeft();
        jPanel1 = new javax.swing.JPanel();
        mapPanel1 = new com.esiee.mbdaihm.view.MapPanel();
        legend1 = new com.esiee.mbdaihm.view.Legend();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("World App");
        setPreferredSize(new java.awt.Dimension(700, 960));

        menuLeft1.setMinimumSize(new java.awt.Dimension(143, 460));
        menuLeft1.setPreferredSize(new java.awt.Dimension(261, 400));
        getContentPane().add(menuLeft1, java.awt.BorderLayout.WEST);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 504));
        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout mapPanel1Layout = new javax.swing.GroupLayout(mapPanel1);
        mapPanel1.setLayout(mapPanel1Layout);
        mapPanel1Layout.setHorizontalGroup(
            mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        mapPanel1Layout.setVerticalGroup(
            mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(mapPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.add(legend1, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public com.esiee.mbdaihm.view.MenuLeft getMenuLeft(){
        return menuLeft1;
    }

    public com.esiee.mbdaihm.view.Legend getLegend(){
        return legend1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.esiee.mbdaihm.view.Legend legend1;
    private com.esiee.mbdaihm.view.MapPanel mapPanel1;
    private com.esiee.mbdaihm.view.MenuLeft menuLeft1;
    // End of variables declaration//GEN-END:variables
}
